name: Ringside
recipe: laravel
config:
  php: '7.3'
  webroot: public
  database: mysql:5.7
  xdebug: true
  config:
    php: .vscode/php.ini
tooling:
  reseed:
    service: appserver
    description: "Seed the database"
    cmd: "php artisan db:seed"
  tinker:
    service: appserver
    description: "Drop into a tinker console"
    cmd: "php artisan tinker"
  ide:
    service: appserver
    description: "Update the IDE docs"
    cmd:
      - "php artisan ide-helper:meta"
      - "php artisan ide-helper:models --write --reset"
  migrate:
    service: appserver
    description: "Quick migrate"
    cmd: "php artisan migrate"
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: "vendor/bin/phpunit --testsuite Feature --coverage-html tests/coverage"
  phpunitdebug:
    service: appserver
    cmd: php -d xdebug.remote_port=9000 vendor/bin/phpunit
