name: Style
on: ['push']
jobs:
  style:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.4]
        laravel: [12]
        stability: [prefer-dist]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - name: "Import GPG key"
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Commit styling changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Fix styling
        commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
        commit_user_name: ${{ steps.import-gpg.outputs.name }}
        commit_user_email: ${{ steps.import-gpg.outputs.email }}
