name: tests
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1']
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: |
          composer install
      - name: Execute lint with Laravel preset
        run: ./pint
      - name: Execute lint with PSR 12 preset
        run: ./pint --preset=psr12
      - name: Execute unit/feature tests
        run: vendor/bin/pest
